trigger:
- main
 
pool:
  name: Default
 
variables:
  buildConfiguration: 'Release'
  webAppName: 'WebAPIEntregaContinua'
  azureSubscription: 'EntregaContinuaService'
 
steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
 
# Cambia 'MySolution.sln' por el nombre real de tu archivo .sln
- script: dotnet restore WebAPIEntregaContinua.sln
  displayName: 'Restore dependencies'
  workingDirectory: '$(Build.SourcesDirectory)'
 
- script: dotnet build WebAPIEntregaContinua.sln --configuration $(buildConfiguration)
  displayName: 'Build project'
  workingDirectory: '$(Build.SourcesDirectory)'
 
- script: dotnet test WebAPIEntregaContinua.sln --configuration $(buildConfiguration) --no-build --verbosity normal
  displayName: 'Run unit tests'
  workingDirectory: '$(Build.SourcesDirectory)'
 
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: true
 
- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop'
 
- task: AzureWebApp@1
  displayName: 'Deploy to Azure WebApp'
  inputs:
    appType: 'webApp'
    azureSubscription: '$(azureSubscription)'
    appName: '$(webAppName)'
    package: '$(Build.ArtifactStagingDirectory)/*.zip'